### ISSUE TITLE
Publish to Terraform Registry

### ISSUE THREAD

**Issue by goedelsoup** [aptible/terraform-provider-aptible#27]
With support for automatic install of third-party plugins available in Terraform 0.13.x, it would be great to publish this provider there so I can run a minimal automation container.

**Comment by robertfairhead** [comment]
We have published our provider to the Terraform registry. It is available at: https://registry.terraform.io/providers/aptible/aptible/latest

The configuration snippet is available on the registry site for automatic install with Terraform 0.13.x

Please be aware that is still quite early for the provider, are in a 0.x beta stage, so there will likely relatively frequent releases and bug fixes for a while, including some breaking changes.
