### ISSUE TITLE
Managed HTTPS endpoints don't publish load balancer hostname 

### ISSUE THREAD

**Issue by derylseale** [aptible/terraform-provider-aptible#37]
When creating managed HTTPS endpoints, we need the load balancer hostname (e.g. elb-shared-us-east-1-wat-99999.aptible.in) in order to create the DNS records required to generate the associated certificate. In this scenario, however, the endpoint resource outputs only the provided domain for the application. 

For example, when creating the following endpoint..
````
resource "aptible_endpoint" "my-endpoint" {
  resource_type  = "app"
  internal       = false
  managed        = true
  domain         = "app.mydomain.com"
  platform       = "alb"
}
````
... the `virtual_domain` output will be "app.mydomain.com" and there is not any other output corresponding to the necessary load balancer hostname. That makes it impossible to use Terraform to create the necessary DNS records automatically.

Would it be possible to add this to the endpoint output? Or is there another way to get this information?

**Comment by robertfairhead** [comment]
Yes, I'll have a PR to add this up soon. I'd expect a new release end of this week/early next week. I'll update here if the timeline will vary significantly from that.

**Comment by robertfairhead** [comment]
Terraform provider v0.1.4 is released at https://registry.terraform.io/providers/aptible/aptible/latest and includes the change to address this.
