### ISSUE TITLE
Managed HTTPS validation domain

### ISSUE THREAD

**Issue by jeremiahbowen** [aptible/terraform-provider-aptible#38]
When creating an aptible endpoint, the aptible_endpoint resources doesn't have an attribute providing the _acme-challenge record that needs to be created to generate a new SSL certificate. This makes it impossible to terraform that DNS record and ensure that it isn't removed in the future (causing an outage when the certificate expires).
Can you update the resource to provide the CNAME and acme host necessary to generate the certificate?
```terraform
resource "aptible_endpoint" "endpoint_testing" {
    container_port = 8080
    default_domain = false
    domain         = "hrz-web-dashboard.domain.com"
    endpoint_id    = ####
    endpoint_type  = "https"
    env_id         = ####
    id             = "####"
    internal       = true
    managed        = true
    platform       = "alb"
    process_type   = "cmd"
    resource_id    = ####
    resource_type  = "app"
    virtual_domain = "hrz-web-dashboard.domain.com"
}
```

**Comment by robertfairhead** [comment]
Yes, I'll be adding that in the forthcoming PR as well per https://github.com/aptible/terraform-provider-aptible/issues/37

**Comment by robertfairhead** [comment]
Terraform provider v0.1.4 is released at https://registry.terraform.io/providers/aptible/aptible/latest and includes the change to address this.
